### ISSUE TITLE
NullPointerException when attempting to get Document from my Elastic Based URL.

### ISSUE THREAD

**Issue by jaswu777** [silverforge/ElasticRawClient#6]
Greetings. I found this yesterday morning and attempted to use it for my Android Project. I followed the instructions clearly to the "T" until I got to where I wanted to get back documents from my Elasticsearch based URL. Below is are the lines of code I used to attempt that task.

ConnectorSettings settings = ConnectorSettings.builder().baseUrl(ELASTIC_URL).indices(ELASTIC_INDICES)
                        .types(ELASTIC_TYPES).userName(ELASTIC_APIKEY).build();
                ElasticClient client = new ElasticClient(settings);

                String[] docIDs = {"AU-dqzzXA9f76l1HgD8C"};
                List<GeofenceEvent> events = client.getDocument(" -d", docIDs, GeofenceEvent.class);

Here is the Stacktrace of the Exception I am getting:

09-16 01:48:22.271  31712-31712/com.example.android.wearable.geofencing E/ExampleGeofencingApp﹕ Error:
    java.lang.NullPointerException
            at com.silverforge.elasticsearchrawclient.utils.StreamUtils.getRawContent(StreamUtils.java:33)
            at com.silverforge.elasticsearchrawclient.elasticFacade.ElasticClient.getDocument(ElasticClient.java:697)
            at com.silverforge.elasticsearchrawclient.elasticFacade.ElasticClient.getDocument(ElasticClient.java:652)
            at com.example.android.wearable.geofencing.MainActivity.addGeofencesButtonHandler(MainActivity.java:644)
            ............

Digging a little deeper into the Exception I found out this is where it giving off the NullPointerException...

    public static String getRawContent(Context context, int rawId) {
        InputStream inputStream = context.getResources().openRawResource(rawId);
        String retValue = convertStreamToString(inputStream);
        return retValue;
    }

The line in question is InputStream inputStream = context.getResources().openRawResource(rawId);

I have checked my input parameters, made sure that the Manifest and Build Gradle script was set properly. I called your framework into my app and tried them in AsyncTask, IntentService, and the main thread to see if it would make any difference and it didn't. I have a feeling that "Context context" is the parameter throwing the NullPointerException. 

I am still an amateur in Android development so please feel free and let me know if I am doing something wrong or anything else. 

Otherwise this is the issue that has been stopping me from fully utilizing the rest of this Client wrapper. Is there a solution that I am missing? Let me know if you need anything else to see! 

Thanks.

**Comment by silverforge** [comment]
Hello Jason,

Thanks for the issue.
I think it's because you are calling my lib from an AsyncTask and there is no access to the context I guess. I'll check it and keep you updated either about the progress or result.

One thing drawn to my attention:

```java
String[] docIDs = {"AU-dqzzXA9f76l1HgD8C"};
            List<GeofenceEvent> events = client.getDocument(" -d", docIDs, GeofenceEvent.class);
```

Here the first parameter of the **getDocument** should be the type of the document. Is the type of your document "-d"? It should be something like "city", "car", "geofence". It's not related to the issue just a heads up :)

**Comment by jaswu777** [comment]
Hey Janos,

I followed your suggestion to use the search Method and it works! In addition, I had to switch the Document type from the unknown generic " -d" to a custom type like "Geofence" and I can now add documents to my Elasticsearch URI. 

Keep me posted on the .getDocument() method! Thanks again for your help and assistance!

**Comment by silverforge** [comment]
Hey Jason,

I've tried to reproduce the issue you posted, but alas I cannot reproduce it. I've tried the following versions : v1.0.0, v1.1.0, v1.1.1 with the same result. (Works as expected)

On this link you can find a sample project, how to retrieve data with **getDocument** method.
https://www.dropbox.com/s/zb8lf3g2xn4d1go/ElasticClientTest.zip?dl=0

In the meantime I released **v1.1.1** which is mostly an structural facelift, maybe worth to give it a try.

One thing what could help you a bit more to understand the **getDocument** mechanism:
It is not necessary to add *type* parameter to the method if you are targeting only one index. In that case when you have multiple indices defined e.g.: ("cities", "cars", "...") and you want to retrieve with documents with that particular type it could come in handy to filter the documents with type parameter. Please check this out : 
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html

The method's *type* parameter is the elastic *_type* field basically.

Hope it helps and please ping me back if you have any results with **getDocument**.

**Comment by jaswu777** [comment]
Greetings,

I have to make this brief for now but I compiled your latest version of the RawClient and tried the getDocument method again this time without adding in the Type field. All I had was 1 single valid ID stored in a String Array and my custom class/object. 

I still got back the exact same error with the NullPointerException pointing to the same lines of code. 

Let me know if you need anything from me and I will post it here later. Thanks.

**Comment by silverforge** [comment]
Hello,

Have you tried the example I mentioned above? That should work properly.

Hm... How do you mean 'compiled'? Only you have to do is to add a new dependency to your **build.gradle** as per doc:

```groovy
dependencies {
    ...
    compile 'com.silverforge.elastic:elasticsearchrawclient:1.1.1'
}
```

I'm afraid if you compiled it by your own the resource files were missing and that could be the reason why the **getDocument** throws the *NullpointerException*, because it tries to retrieve the query I sent to you earlier from *res* file

Please open the sample app I linked above with latest android studio and there is a straightforward example how you should add the **ElasticRawClient** library to dependecies properly and there is a working example for **getDocument**.

Let me know if you have any progress on that. 

Cheers

**Comment by jaswu777** [comment]
Thank you. I was in a rush last time but this time I had time to check out the sample app and run it separately on my phone: it works as expected. 

In regards to my "compilation" comment, that is what I meant actually. I did follow instructions and typed in "compile 'your latest path version'".

So I'm still not exactly sure why it works perfectly fine in your example and why just the method .getDocument doesn't work on my own application. 
.search method and add method works wonders on the other hand on my application.

I do have the code running in AsyncTask alongside IntentService. Both are in those background threads simultaneously. 

Thanks again.
